---
title: "Research pipeline"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: yeti
    navbar: 
      - { icon: "fas fa-database", href: "https://airtable.com/tblXj4OTLat3kWEAE", align: right}
runtime: shiny
---

```{r eval=FALSE, include=FALSE}
# https://github.com/lhehnke/project-killR
```

```{r setup, include=FALSE}
library(tidyverse)
library(airtabler)
library(flexdashboard)
library(plotly)
library(pluralize)
library(lubridate)

source(".secrets/airtable-api.R")
```

```{r global, include=FALSE}
pipeline_base <- airtable("appw9GaXRQ9sCEUtT", c("Papers", "Scores", "Submissions"))
```

```{r get-pipeline-data, message=FALSE, include=FALSE}
load_data <- function() {
  scores <- pipeline_base$Scores$select_all(fields = list("Status", "Score")) %>% 
    mutate(Status_plot = str_replace_all(Status, "; ", ";\n"),
           Status_plot = str_replace_all(Status_plot, "Presented at ", "Presented at\n"),
           Status_plot = str_replace_all(Status_plot, "review post", "review\npost")) %>% 
    mutate(point_text = map_chr(Score, ~pluralize("point", n = .)),
           Status_plot = paste0(Status_plot, "\n(", Score, " ", point_text, ")")) %>% 
    select(-createdTime, -point_text) %>% 
    rename(score_id = id) %>% 
    arrange(desc(Score))
  
  pipeline <- pipeline_base$Papers$select_all(fields = list("Paper", "Status", "Most recent date")) %>% 
    mutate(`Most recent date` = ymd(`Most recent date`)) %>% 
    mutate(Status = unlist(Status)) %>% 
    rename(paper_id = id, score_id = Status) %>% 
    left_join(scores, by = "score_id") %>% 
    filter(!(`Most recent date` < ymd("2019-06-01") & Status == "Accepted"))
  
  return(list(scores = scores, pipeline = pipeline))
}

pipeline_raw <- load_data()

scores <- pipeline_raw$scores
pipeline <- pipeline_raw$pipeline
```


## Row

### Current projects {.value-box}

```{r}
num_projects <- nrow(pipeline)

renderValueBox({
  valueBox(num_projects, icon = "fas fa-tasks", color = "#FFDC00")
})
```

### Total points {.value-box}

```{r}
total_points <- sum(pipeline$Score)

renderValueBox({
  valueBox(total_points, icon = "fas fa-chart-bar", color = "#FF851B") 
})
```

### Average points {.value-box}

```{r}
avg_points <- mean(pipeline$Score) %>% round(2)

renderValueBox({
  valueBox(avg_points, icon = "fas fa-thermometer-half", color = "#7FDBFF") 
})
```

### Standard deviation of points {.value-box}

```{r}
sd_points <- sd(pipeline$Score) %>% round(2)

renderValueBox({
  valueBox(sd_points, icon = "fas fa-heartbeat", color = "#7FDBFF")
})
```

## Row

###

```{r warning=FALSE}
pipeline_tiles <- pipeline %>% 
  mutate(score_cat = factor(Score, 
                            levels = c(7, 6, 5, 4, 3.5, 3, 2, 1, 0),
                            labels = scores$Status_plot)) %>% 
  mutate(x = as.numeric(score_cat)) %>% 
  group_by(score_cat) %>% 
  mutate(y = 1:n()) %>% 
  ungroup()

plot_pipeline <- ggplot(pipeline_tiles) +
  geom_rect(aes(xmin = x + 0.05, xmax = x + 0.95, 
                ymin = y + 0.025, ymax = y + 0.975,
                text = Paper), fill = "#0074D9") +
  scale_x_continuous(breaks = seq(1.5, 10.5, 1), 
                     labels = c(scores$Status_plot, "asdf"),
                     expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(1, 25, 5)) +
  labs(x = NULL, y = NULL) +
  theme_minimal(base_size = 14, base_family = "Open Sans") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

renderPlotly({
  ggplotly(plot_pipeline, tooltip = "text")
})
```
